FROM ubuntu

RUN apt-get update -y
RUN apt install nodejs -y
RUN apt-get -y upgrade
RUN apt-get install python -y
RUN apt-get update -y
RUN apt-get install gcc -y
RUN apt-get update -y
RUN apt-get install g++ -y
RUN apt-get update -y
RUN apt install default-jdk -y
RUN apt install openjdk-11-jdk-headless -y
RUN apt install ecj -y
RUN apt install openjdk-8-jdk-headless -y
RUN apt-get update -y
RUN apt-get install time -y
RUN mkdir app