FROM ubuntu

RUN apt-get update -y
RUN apt install nodejs -y
RUN apt-get -y upgrade
RUN apt-get install python -y
RUN apt-get update -y
RUN apt-get install gcc -y
RUN apt-get update -y
RUN apt-get install g++ -y
RUN mkdir app