export const SET_OUTPUT = 'SET_OUTPUT';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';
export const SET_AUTH_FAILURE = 'SET_AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const INTERVIEW_LINK_GENERATION_SUCCESS =
  'INTERVIEW_LINK_GENERATION_SUCCESS';
export const INTERVIEW_LINK_GENERATION_FAILURE =
  'INTERVIEW_LINK_GENERATION_FAILURE';
export const SET_INTERVIEW_LINK_LOADING_TRUE =
  'SET_INTERVIEW_LINK_LOADING_TRUE';
